### ISSUE TITLE
docker-compose pull results in error

### ISSUE THREAD

**Issue by teejo75** [linuxserver/docker-readarr#2]
Using your sample docker-compose.yml iun your `readme.md`, when doing `docker-compose pull` I get:
```
Pulling readarr ... error

ERROR: for readarr  name unknown
ERROR: name unknown
```

If I change the image to simply linuxserver/readarr, I get:
```
Pulling readarr ... error

ERROR: for readarr  manifest for linuxserver/readarr:latest not found: manifest unknown: manifest unknown
ERROR: manifest for linuxserver/readarr:latest not found: manifest unknown: manifest unknown
```

**Comment by Roxedus** [comment]
Our readme does not say :latest is a valid tag

**Comment by j0nnymoe** [comment]
As per our readme, there is only a nightly tag: https://github.com/linuxserver/docker-readarr#version-tags

**Comment by NemesisRE** [comment]
but the readme does say there is a latest in the recommended compose part it doesn't add a tag which results in latest
https://github.com/linuxserver/docker-readarr#docker-compose-recommended-click-here-for-more-info

**Comment by j0nnymoe** [comment]
Those are examples: `Here are some example snippets to help you get started creating a container.`

The recommended is suggesting that compose is our recommended deployment method. You should still be checking what tags are available in the table above.

**Comment by NemesisRE** [comment]
Yes sure but an example that doesn't work is a bad or at least missleading. If there is only one tag wouldn't it be better to added that tag to the example.
On the other hand if there is only one tag it's also the latest so you could double tag nightly with latest until you switch it to a production version.
It is just an suggestion IMHO an example should work to be an example.

But I don't wanted to sound ungrateful I am thankful for your work keep it up!

**Comment by Roxedus** [comment]
The reasoning for it being the way it is, is because Readarr is still beta, and it's not guaranteed to work the way you may expect (but it also isn't guaranteed to break). Having a user not blindly follow a example helps us make sure the user is somewhat invested in this.

**Comment by facorazza** [comment]
The readme could still be improved regardless

**Comment by PsychoData** [comment]
@Roxedus 

the Contributing document [says to edit the readme-vars.yml](https://github.com/linuxserver/docker-readarr/blob/main/.github/CONTRIBUTING.md#:~:text=the%20README.md-,Readme,-If%20you%20would) but there is no readme-vars.yml file to modify to fix the ReadMe file. 

The [Usage section](https://github.com/linuxserver/docker-readarr#usage) of the current ReadMe file has docker-compose and docker CLI setups that do not work (because Latest is not a valid Tag, as mentioned above). The Image is specified as `ghcr.io/linuxserver/readarr` which doesn't handle the need to use `:nightly` . 

It looks like switching to `ghcr.io/linuxserver/readarr:nightly` will at least make it so that the commands on the readme page will work - and it could be tweaked back to `ghcr.io/linuxserver/readarr` with no tag whenever it is time for normal release. 

There are several other places on the Readme that also mention JUST `ghcr.io/linuxserver/readarr` or `linuxserver/readarr` or `readarr` where it also should get changed if you want the commands mentioned on the Readme page to be correct/work. 

So, I'm not sure if we need to just edit the Readme.md directly right now, or figure out what to put in the readme-vars.yml to match the existing Readme.md. Is there something to describe the build process for the readme, so we can fix it?

**Comment by Roxedus** [comment]
This is done with intention, readarr is in beta, so we highly recommend users to read and understand the readme, which does state which tags are active.

**Comment by PsychoData** [comment]
Ah, so it's intentionally left with broken commands and no direct explanation because you only want people who can put together that `docker pull linuxserver/readarr` is going to pull `:latest` by default - and since `:latest` is NOT listed that is why all of the examples are broken. 

If you don't want people to follow examples - just remove the examples

**Comment by Roxedus** [comment]
They are just that, examples.

**Comment by jt196** [comment]
Came here to figure this out. 

Honestly, I'd probably leave the image tag on the sample docker-compose file to something that's working, even though it's in beta. 

IMHO Better to have an off the bat working docker-compose file and some explanation about the tag usage than have (potentially) some folks drop out from frustration.

**Comment by MitchTalmadge** [comment]
I just ran into this. The README of this container says both:

> Simply pulling `ghcr.io/linuxserver/readarr` should retrieve the correct image for your arch

and 

> `latest` tag usually provides the latest stable version.

Yet this repository has no latest tag; both of those statements are incorrect and/or misleading. 

> we highly recommend users to read and understand the readme

That is fine, but we expect the readme to be understandable. This means not telling people that they can "simply pull `ghcr.io/linuxserver/readarr`" or mention the `latest` tag when it does not exist.

**Comment by aptalca** [comment]
Neither statement is incorrect. The first statement is only about `arch`, as in you don't need an arch specific tag like `nightly-arm32v7`. The second one simply states `latest` usually provides the latest stable. This (upstream) project does not have a stable release, thus no `latest` tag. When there is a stable upstream release, there will be a `latest` tag.

The table under `Version Tags` lists all available tags.

Our readmes are templated and contain generalized statements that may not apply to all the images (they apply to a great majority). However they are rarely incorrect.

**Comment by MitchTalmadge** [comment]
I see, thank you for replying
