### ISSUE TITLE
Missing tag in dockerhub: latest

### ISSUE THREAD

**Issue by mwarkentin** [linuxserver/docker-readarr#40]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I can download `latest` tag of linuxserver/readarr successfully.

## Current Behavior

docker pull fails:

```
sudo docker pull linuxserver/readarr:latest
Error response from daemon: manifest for linuxserver/readarr:latest not found: manifest unknown: manifest unknown
```

## Steps to Reproduce

1. `sudo docker pull linuxserver/readarr:latest`

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/ab9d77c2-8979-49dd-b7a1-1706e2d09151">

## Environment
**OS: Synology**
**CPU architecture:** x86_64
**How docker service was installed:**

**Comment by Roxedus** [comment]
There is no stable release of readarr, therefore no latest tag. as shown in the readme
![image](https://github.com/user-attachments/assets/9ed07137-1277-4522-80ee-908ee5a4e089)

**Comment by mwarkentin** [comment]
Thanks, didn't realize that was a requirement. 👍

**Comment by auspex** [comment]
It's all very understandable that you don't want to support Readarr anymore, but did you have to break the image as well?

I can no longer pull readarr using either the `nightly` tag (which is what I used before) or `develop`, because of the same manifest problem. What _is_ a valid tag?

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-readarr/pkgs/container/readarr
All the ones listed here.
The reason we break the latest tag is to stop people thinking they're still getting updates when in reality we haven't touched it.

**Comment by aptalca** [comment]
We didn't break the image. We just no longer allow pulling the rolling latest and similar tags so as not to give users the false sense of security or the impression that they may be getting updates. 

The project has been deprecated not just by us but also by the upstream devs. The app is not getting any updates from us or the upstream project. The app is not supported by us or the upstream project. 

But since everything we do is open, you are free to pull any static image tag we previously pushed to docker hub, ghcr, gitlab and quay. You can also modify the source files and build your own images.
